In [8]:
#Nama   : Mia Amaliah
#NIM    : 1202922002
#Tugas : Multinomial Regression

import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/network-detection/Train.txt


In [9]:
data = pd.read_csv("/kaggle/input/network-detection/Train.txt",sep=",",names=["duration","protocoltype","service","flag","srcbytes","dstbytes","land", "wrongfragment","urgent","hot","numfailedlogins","loggedin", "numcompromised","rootshell","suattempted","numroot","numfilecreations", "numshells","numaccessfiles","numoutboundcmds","ishostlogin",
"isguestlogin","count","srvcount","serrorrate", "srvserrorrate",
"rerrorrate","srvrerrorrate","samesrvrate", "diffsrvrate", "srvdiffhostrate","dsthostcount","dsthostsrvcount","dsthostsamesrvrate", "dsthostdiffsrvrate","dsthostsamesrcportrate",
"dsthostsrvdiffhostrate","dsthostserrorrate","dsthostsrvserrorrate",
"dsthostrerrorrate","dsthostsrvrerrorrate","attack", "lastflag"])
data.head()

duration protocoltype   service flag  srcbytes  dstbytes  land  \
0         0          tcp  ftp_data   SF       491         0     0   
1         0          udp     other   SF       146         0     0   
2         0          tcp   private   S0         0         0     0   
3         0          tcp      http   SF       232      8153     0   
4         0          tcp      http   SF       199       420     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.17                0.03   
1              0       0    0  ...                0.00                0.60   
2              0       0    0  ...                0.10                0.05   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                1.00                0.00   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.17                    0.00               0.00   
1                    0.88                    0.00               0.00   
2                    0.00                    0.00               1.00   
3                    0.03                    0.04               0.03   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate   attack  \
0                  0.00               0.05                  0.00   normal   
1                  0.00               0.00                  0.00   normal   
2                  1.00               0.00                  0.00  neptune   
3                  0.01               0.00                  0.01   normal   
4                  0.00               0.00                  0.00   normal   

   lastflag  
0        20  
1        15  
2        19  
3        21  
4        21  

[5 rows x 43 columns]

In [10]:
data.dtypes

duration                    int64
protocoltype               object
service                    object
flag                       object
srcbytes                    int64
dstbytes                    int64
land                        int64
wrongfragment               int64
urgent                      int64
hot                         int64
numfailedlogins             int64
loggedin                    int64
numcompromised              int64
rootshell                   int64
suattempted                 int64
numroot                     int64
numfilecreations            int64
numshells                   int64
numaccessfiles              int64
numoutboundcmds             int64
ishostlogin                 int64
isguestlogin                int64
count                       int64
srvcount                    int64
serrorrate                float64
srvserrorrate             float64
rerrorrate                float64
srvrerrorrate             float64
samesrvrate               float64
diffsrvrate   

In [11]:
data.shape

(125973, 43)

In [12]:
data.describe ()

duration      srcbytes      dstbytes           land  wrongfragment  \
count  125973.00000  1.259730e+05  1.259730e+05  125973.000000  125973.000000   
mean      287.14465  4.556674e+04  1.977911e+04       0.000198       0.022687   
std      2604.51531  5.870331e+06  4.021269e+06       0.014086       0.253530   
min         0.00000  0.000000e+00  0.000000e+00       0.000000       0.000000   
25%         0.00000  0.000000e+00  0.000000e+00       0.000000       0.000000   
50%         0.00000  4.400000e+01  0.000000e+00       0.000000       0.000000   
75%         0.00000  2.760000e+02  5.160000e+02       0.000000       0.000000   
max     42908.00000  1.379964e+09  1.309937e+09       1.000000       3.000000   

              urgent            hot  numfailedlogins       loggedin  \
count  125973.000000  125973.000000    125973.000000  125973.000000   
mean        0.000111       0.204409         0.001222       0.395736   
std         0.014366       2.149968         0.045239       0.489010   
min         0.000000       0.000000         0.000000       0.000000   
25%         0.000000       0.000000         0.000000       0.000000   
50%         0.000000       0.000000         0.000000       0.000000   
75%         0.000000       0.000000         0.000000       1.000000   
max         3.000000      77.000000         5.000000       1.000000   

       numcompromised  ...  dsthostsrvcount  dsthostsamesrvrate  \
count   125973.000000  ...    125973.000000       125973.000000   
mean         0.279250  ...       115.653005            0.521242   
std         23.942042  ...       110.702741            0.448949   
min          0.000000  ...         0.000000            0.000000   
25%          0.000000  ...        10.000000            0.050000   
50%          0.000000  ...        63.000000            0.510000   
75%          0.000000  ...       255.000000            1.000000   
max       7479.000000  ...       255.000000            1.000000   

       dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
count       125973.000000           125973.000000           125973.000000   
mean             0.082951                0.148379                0.032542   
std              0.188922                0.308997                0.112564   
min              0.000000                0.000000                0.000000   
25%              0.000000                0.000000                0.000000   
50%              0.020000                0.000000                0.000000   
75%              0.070000                0.060000                0.020000   
max              1.000000                1.000000                1.000000   

       dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
count      125973.000000         125973.000000      125973.000000   
mean            0.284452              0.278485           0.118832   
std             0.444784              0.445669           0.306557   
min             0.000000              0.000000           0.000000   
25%             0.000000              0.000000           0.000000   
50%             0.000000              0.000000           0.000000   
75%             1.000000              1.000000           0.000000   
max             1.000000              1.000000           1.000000   

       dsthostsrvrerrorrate       lastflag  
count         125973.000000  125973.000000  
mean               0.120240      19.504060  
std                0.319459       2.291503  
min                0.000000       0.000000  
25%                0.000000      18.000000  
50%                0.000000      20.000000  
75%                0.000000      21.000000  
max                1.000000      21.000000  

[8 rows x 39 columns]

In [13]:
data.drop(['protocoltype','service','flag'],axis=1,inplace=True)

In [14]:
data.isna().sum()

duration                  0
srcbytes                  0
dstbytes                  0
land                      0
wrongfragment             0
urgent                    0
hot                       0
numfailedlogins           0
loggedin                  0
numcompromised            0
rootshell                 0
suattempted               0
numroot                   0
numfilecreations          0
numshells                 0
numaccessfiles            0
numoutboundcmds           0
ishostlogin               0
isguestlogin              0
count                     0
srvcount                  0
serrorrate                0
srvserrorrate             0
rerrorrate                0
srvrerrorrate             0
samesrvrate               0
diffsrvrate               0
srvdiffhostrate           0
dsthostcount              0
dsthostsrvcount           0
dsthostsamesrvrate        0
dsthostdiffsrvrate        0
dsthostsamesrcportrate    0
dsthostsrvdiffhostrate    0
dsthostserrorrate         0
dsthostsrvserrorrate

In [15]:
data.select_dtypes(exclude=[np.number])

attack
0        normal
1        normal
2       neptune
3        normal
4        normal
...         ...
125968  neptune
125969   normal
125970   normal
125971  neptune
125972   normal

[125973 rows x 1 columns]

In [16]:
x=data.drop(['attack'],axis=1).values
y=data['attack'].values

print (x)


[[0.000e+00 4.910e+02 0.000e+00 ... 5.000e-02 0.000e+00 2.000e+01]
 [0.000e+00 1.460e+02 0.000e+00 ... 0.000e+00 0.000e+00 1.500e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 1.900e+01]
 ...
 [0.000e+00 2.231e+03 3.840e+02 ... 1.000e-02 0.000e+00 1.800e+01]
 [0.000e+00 0.000e+00 0.000e+00 ... 0.000e+00 0.000e+00 2.000e+01]
 [0.000e+00 1.510e+02 0.000e+00 ... 0.000e+00 0.000e+00 2.100e+01]]


In [17]:
print (y)

['normal' 'normal' 'neptune' ... 'normal' 'neptune' 'normal']


In [18]:
x_train,x_test,y_train,y_test=train_test_split (x,y,test_size=0.3,random_state =1)
x_train


array([[0.0000e+00, 1.0044e+04, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.8000e+01],
       [0.0000e+00, 1.9800e+02, 2.9300e+02, ..., 0.0000e+00, 0.0000e+00,
        2.1000e+01],
       [0.0000e+00, 1.0320e+03, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        1.8000e+01],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        2.1000e+01],
       [0.0000e+00, 2.4600e+02, 3.7490e+03, ..., 0.0000e+00, 4.2000e-01,
        2.1000e+01],
       [0.0000e+00, 4.4000e+01, 4.4000e+01, ..., 0.0000e+00, 0.0000e+00,
        2.0000e+01]])

In [19]:
y_train

array(['normal', 'normal', 'smurf', ..., 'neptune', 'normal', 'normal'],
      dtype=object)

In [21]:
model=LogisticRegression()
model.fit(x_train,y_train)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [22]:
model.predict_proba(x_test)[0:5]

array([[0.04457889, 0.04215249, 0.04213773, 0.04213327, 0.04213359,
        0.04217373, 0.0421319 , 0.04213529, 0.04233289, 0.04413529,
        0.04216076, 0.05311921, 0.04213259, 0.04213542, 0.04214599,
        0.04957923, 0.04213676, 0.04231421, 0.04250289, 0.04213232,
        0.04217701, 0.04376989, 0.04764863],
       [0.06131195, 0.03942525, 0.03941366, 0.03941497, 0.03941489,
        0.0394465 , 0.03941319, 0.03941354, 0.03941276, 0.04180416,
        0.03944011, 0.06303895, 0.03941342, 0.03941323, 0.03952399,
        0.06134672, 0.03941443, 0.03966722, 0.04084148, 0.03941334,
        0.03945345, 0.06132105, 0.03924176],
       [0.04435987, 0.04323904, 0.04323832, 0.04323845, 0.04323839,
        0.04324138, 0.04323829, 0.04323831, 0.04323823, 0.04368684,
        0.04324301, 0.04481491, 0.04323832, 0.04323834, 0.04324609,
        0.04436617, 0.04323846, 0.04327728, 0.04331835, 0.04323833,
        0.04324824, 0.0443558 , 0.04321959],
       [0.0441979 , 0.04314231, 0.04314163, 0.043

In [23]:
predictions=model.predict(x_test)
predictions

array(['normal', 'normal', 'normal', ..., 'neptune', 'neptune', 'normal'],
      dtype=object)

In [24]:
print (classification_report(y_test,predictions))

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


                 precision    recall  f1-score   support

           back       0.00      0.00      0.00       271
buffer_overflow       0.00      0.00      0.00        12
      ftp_write       0.00      0.00      0.00         2
   guess_passwd       0.00      0.00      0.00        24
           imap       0.00      0.00      0.00         2
        ipsweep       0.00      0.00      0.00      1114
           land       0.00      0.00      0.00         4
     loadmodule       0.00      0.00      0.00         2
       multihop       0.00      0.00      0.00         2
        neptune       0.88      0.94      0.91     12283
           nmap       0.00      0.00      0.00       461
         normal       0.83      0.97      0.89     20266
           perl       0.00      0.00      0.00         1
            phf       0.00      0.00      0.00         1
            pod       0.00      0.00      0.00        46
      portsweep       0.30      0.35      0.33       821
        rootkit       0.00    

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [25]:
print ("akurasi hasil prediksi")
print (accuracy_score(y_test,predictions))

akurasi hasil prediksi
0.8307313717188823
